function [layout,rotation]=uea_map(patient)
% UEA_MAP  Generate proper layout of the NS5 channels
%    Data are taken from the Excel spreadsheets generated by Blackrock
%    (Cerebus) and are stored internally in this script in two columns: 
%    p2e(:,1) are pins; p2e(:,2) are electrodes.  Pins correspond to the 
%    NS5 channel index.  Electrodes are always mapped like this:
%
%    91 ... 100
%       ...
%     1 ... 10
%
%    The first returned matrix, if displayed on at the command line, shows 
%    the UEA as seen from the top down (pointy tips facing down), with the 
%    wire bundle extending from the righthand side (e.g., from electrodes 
%    [10 20 30 ... 100] in the electrode map).  Unmapped pins come back as
%    NaN.
%
%    The second returned variable indicates the rotation of the UEA
%    relative to a position in which the wire bundle extends toward the 
%    righthand side of the page (regardless of brain orientation).
%
%    In the Excel spreadsheets, the center block of cells describes the 
%    pin-to-electrode mapping.  The "pin # column" describes the number 
%    that corresponds to the NS5 index and goes 1 3 5 ... 31 in the
%    lefthand side, and 2 4 6 ... 32 in the righthand side.  Disregard
%    33-36 at the bottom (in gray).  In the blocks of cells without pin
%    columns (IDC's B and C), add 32 or 64 (respectively) to get the
%    correct pin numbers.
%
%    Example:
%    [layout,rotation]=uea_map('nu'); % layout and rotation for 'nu'
%    >> layout
%
%    ans =
%
%       NaN     2     1     3     4     6     8    10    14   NaN
%        65    66    33    34     7     9    11    12    16    18
%        67    68    35    36     5    17    13    23    20    22
%        69    70    37    38    48    15    19    25    27    24
%        71    72    39    40    42    50    54    21    29    26
%        73    74    41    43    44    46    52    62    31    28
%        75    76    45    47    51    56    58    60    64    30
%        77    78    82    49    53    55    57    59    61    32
%        79    80    84    86    87    89    91    94    63    95
%       NaN    81    83    85    88    90    92    93    96   NaN
%
%   In the above example, the wire bundle comes off the the pins [18 22 24
%   26 28 30 32 95].
%

% electrode map as described above
% wire bundle comes off the righthand side
elmap=[ 91:100;
        81:90;
        71:80;
        61:70;
        51:60;
        41:50;
        31:40;
        21:30;
        11:20;
         1:10; ];

switch(patient)
    
    case 'frak'
        % patient: Frak
        % array serial #: 1024-0342
        p2e=[...
            1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96; ...
            93  92  94  95  75  96  85  97  86  98  87  88  77  99  66  89  76  90  67  79  58  80  78  70  68  60  69  50  59  40  49  30  83  84  73  74  63  64  53  54  43  55  44  45  33  46  34  65  24  56  35  47  25  57  26  36  27  37  28  38  29  48  19  39  81  82  71  72  61  62  51  52  41  42  31  32  21  22  11  12   2  23   3  13   4  14  15   5  16   6  17   7   8  18  20  9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

    case 'epsilon'
        % patient: Epsilon
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees
        
    case 'gamma'
        % patient: Gamma
        % year/mo.: 2008-06
        % array serial #: 4382-139
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            91	1	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	100	10	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=150; % rotation in degrees
        
    case 'kappa'
        % patient: Kappa
        % year/mo.: 2009-03
        % array serial #: 4382-192
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=190; % rotation in degrees
        
    case 'lambda'
        % patient: Lambda
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

    case 'nu'
        % patient: Nu
        % year/mo.: 2009-07 to 2009-08
        % array serial #: 4382-0375
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=45; % rotation in degrees

    case 'patient-02'
        % patient: Patient-02 (Columbia)
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

    case 'patient-04'
        % patient: Patient-04 (Columbia)
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

    case 'patient-05'
        % patient: Patient-05 (Columbia)
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

    case 'patient-07'
        % patient: Patient-07 (Columbia)
        % COPIED FROM PATIENT NU
        p2e=[...
            1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	32	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	34	36	38	40	42	44	46	48	50	52	54	56	58	60	62	64	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	66	68	70	72	74	76	78	80	82	84	86	88	90	92	94	96; ...
            93	94	75	85	86	87	77	66	76	67	58	78	68	69	59	49	92	95	96	97	98	88	99	89	90	79	80	70	60	50	40	30	83	73	63	53	43	44	33	34	24	35	25	26	27	28	29	19	84	74	64	54	55	45	46	65	56	47	57	36	37	38	48	39	81	71	61	51	41	31	21	11	2	3	4	15	16	17	8	20	82	72	62	52	42	32	22	12	23	13	14	5	6	7	18	9; ...
        ]'; % pin-to-electrode mapping
        rotation=0; % rotation in degrees

end

layout=nan(10,10);
for k=1:size(p2e,1)
    layout(elmap==p2e(k,2))=p2e(k,1);
end