function Hd = notchfilter
%NOTCHFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-May-2015 09:40:30

% IIR Comb Notching filter designed using the IIRCOMB function.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

N     = 10;  % Order
BW    = 2;   % Bandwidth
Apass = 1;   % Bandwidth Attenuation

[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
