function SyncStruct = genSyncStruct(SyncSignal)

% This function converts the SyncSignal that was recorded in Cerebus and
% generated by the SyncTask.vi in Labview to a structure of timestamps. The
% Cerebus recording must be 2kS/s. SyncSignal consists of patterns of 0 or
% 5 volts that represent a date in u32 format. Each 32-bit date is preceded
% by a header that is 10 bits of 5 volts followed by 1 bit of 0 volts. The
% bits are written by the Labview task to Cerebus at 10 Hz intervals.
%
% Version Date: 20111016
% Author: Tyler Davis

Fs = 2000; % Sync signal must be recorded at 2kS/s
MaxSyncTSLength = 4.3*Fs; % Units samples. Timestamps in sync signal are 43 bits long and sent at a rate of 10 Hz.
MinSyncTSPeriod = 10*Fs; % Units samples. Timestamps in sync signal can have a minimum period of 10 sec.
BitLength = 0.1*Fs; % Units samples.

% Finding voltages (Values) for each timestamp (TS) in the SyncSignal
[SyncIdxs, SyncMS] = PulseCounter(SyncSignal,Fs,10000);
SyncTSStartIdxs = SyncIdxs([1,find(diff(SyncIdxs)>MaxSyncTSLength)+1])';
SyncTSStartIdxsMat = repmat(SyncTSStartIdxs,1,MaxSyncTSLength) + repmat(0:MaxSyncTSLength-1,size(SyncTSStartIdxs,1),1);
SyncTSValues = SyncSignal(SyncTSStartIdxsMat);

% Finding the voltage values at the middle of each 200 sample bit (43 total)
SyncTSBits = SyncTSValues(:,100:BitLength:MaxSyncTSLength-100)>10000;

% Converting to decimal
SyncTSBitsStr = num2str(fliplr(SyncTSBits(:,12:end))')';
SyncTSBitsStr = SyncTSBitsStr(1:3:size(SyncTSBitsStr,1),:);
SyncTSSec = bin2dec(SyncTSBitsStr);

% Convert from Labview to Matlab time (64800 represents seconds in 18 hours)
Labview2MatlabOffset = etime(datevec('01-01-1904 00:00:00','mm-dd-yyyy HH:MM:SS'),datevec('01-01-0000 00:00:00','mm-dd-yyyy HH:MM:SS')) + 64800;
SyncTSDays = (SyncTSSec + Labview2MatlabOffset)/86400;
SyncTSDateVec = datevec(SyncTSDays);

% Saving to Structure
for k=1:size(SyncTSDateVec,1)    
    SyncStruct(k).Date = SyncTSDateVec(k,:);
    SyncStruct(k).Samples = SyncTSStartIdxs(k);
    SyncStruct(k).Seconds = SyncTSStartIdxs(k)/Fs;            
end






